sudo: required
services:
- docker

before_install:
- docker build -t dinhhuyams/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run dinhhuyams/react-test npm test -- --coverage

after_success:
- docker build -t dinhhuyams/multi-client ./client
- docker build -t dinhhuyams/multi-nginx ./nginx
- docker build -t dinhhuyams/multi-server ./server
- docker build -t dinhhuyams/multi-worker ./worker
# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take those images and push them to docker hub
- docker push dinhhuyams/multi-client
- docker push dinhhuyams/multi-nginx
- docker push dinhhuyams/multi-server
- docker push dinhhuyams/multi-worker
